name: Radar Courvan

on:
  push:
    branches:
      - main
      
jobs:
  executar-radar:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm install

      - name: Executar Radar
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: node radar.js

      - name: Salvar oportunidades.json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add oportunidades.json
          git commit -m "Atualizando oportunidades automaticamente" || echo "Sem alterações"
          git push
